### ISSUE TITLE
Treinamento Git

### ISSUE THREAD

**Issue by MarcosNBJ** [fga-eps-mds/2021-2-Cartografia-social-Doc#1]
Dojo sobre Git, abrangendo os tópicos:

- [x] O que é git
- [x] Git e Github
- [x] Utilidade
- [x] Comandos
- [x] Contribuição com projetos parceiros

**Comment by RafaellaJunqueira** [comment]
Treinamento realizado dia 31/01 às 19 horas. Gravação disponível no canal do Teams.
