### ISSUE TITLE
Solicitar cadastro de usuário

### ISSUE THREAD

**Issue by MarcosNBJ** [fga-eps-mds/2021-2-Cartografia-social-Doc#70]
## Descrição
Eu, como usuário, gostaria de solicitar o meu cadastro através do aplicativo.

## Critérios de aceitação

- [ ] Possível usuário consegue solicitar cadastro através do aplicativo ao preencher um formulário

## Tarefas

- [x] Tela do formulário no aplicativo
- [x] Envio da solicitação ao backend
- [x] Criação do endpoint no backend
- [ ] Campo **obrigatório** -> "Você é membro da comunidade ou pesquisador? Opções dropdown: membro, pesquisador, membro e pesquisador"
- [ ] Criar campo **opcional** -> Um campo para a pessoa colocar um cargo (**Ideia:** colocar uma parte já preenchida default de como "Cargo/ Afiliação" e se a pessoa preencher, aparece preenchido na frente disso. Caso contrário, fica vazio mesmo)
- [x] Aparecer uma mensagem após enviado o formulário: "Solicitação enviada! Você será informado via email após aprovação do cadastro"

**Comment by gustavomartins-github** [comment]
A Tela do formulário no aplicativo foi concluída. Agora trabalharei no envio da solicitação ao backend.

**Comment by gustavomartins-github** [comment]
O endpoint foi criado conforme solicitado. Tive forte auxilio do @Eric-chagas para conclusão dessa tarefa. Agora trabalharei no envio da solicitação ao Backend.

**Comment by Peedrooo** [comment]
## Conexão front brack realizada

- Envio de solicitação ao back
- Mensagem de confirmação incrementada
- Validação de preenchimento de campos
- Validação de correspondência de senhas

## Bugs
- Valor do dropdown comunidades vindo como undefined

**Comment by Peedrooo** [comment]
Bug no drop corrigido
